// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDawFB3DbjYKrPNj39vNufZ4JuDw9QBIVg',
    appId: '1:758788665844:web:63499c4ed0d08360cac9a1',
    messagingSenderId: '758788665844',
    projectId: 'kullanicigiris-f545a',
    authDomain: 'kullanicigiris-f545a.firebaseapp.com',
    storageBucket: 'kullanicigiris-f545a.firebasestorage.app',
    measurementId: 'G-ENL78LCTKV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDV_WBMn6t2-kQB4HYtF-h_1xmPPb7OvpA',
    appId: '1:758788665844:android:3e4b07902a16305dcac9a1',
    messagingSenderId: '758788665844',
    projectId: 'kullanicigiris-f545a',
    storageBucket: 'kullanicigiris-f545a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgVmnZlwT_alhatocF5NPSY0-GhSKd9vE',
    appId: '1:758788665844:ios:1a54815d08abf165cac9a1',
    messagingSenderId: '758788665844',
    projectId: 'kullanicigiris-f545a',
    storageBucket: 'kullanicigiris-f545a.firebasestorage.app',
    iosBundleId: 'com.example.deneme',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgVmnZlwT_alhatocF5NPSY0-GhSKd9vE',
    appId: '1:758788665844:ios:1a54815d08abf165cac9a1',
    messagingSenderId: '758788665844',
    projectId: 'kullanicigiris-f545a',
    storageBucket: 'kullanicigiris-f545a.firebasestorage.app',
    iosBundleId: 'com.example.deneme',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDawFB3DbjYKrPNj39vNufZ4JuDw9QBIVg',
    appId: '1:758788665844:web:2f4aaa1fce103e4fcac9a1',
    messagingSenderId: '758788665844',
    projectId: 'kullanicigiris-f545a',
    authDomain: 'kullanicigiris-f545a.firebaseapp.com',
    storageBucket: 'kullanicigiris-f545a.firebasestorage.app',
    measurementId: 'G-LZ8P6JCTW8',
  );
}
